#!/usr/bin/env node

var semver = require('semver');
var version;

version = process.argv[2];
version = semver.inc(version, 'minor')

console.log(version);

// Local Variables:
// mode: javascript-mode
// End:
