#!/usr/bin/env bash

echo "Git post-checkout hook."

start() {
    (
	cd $(git rev-parse --git-dir)/hooks
	npm i
	npm start
    )
}

stop() {

}

if [ ! -z ${CLOCK+x} ]; then
    
    case "$CLOCK" in
	# if CLOCK in then run server
	'in')
            start
            ;;
	'out')
            stop
            ;;
	*)
            echo
            echo "Usage: $0 { in | out }"
            echo
            exit 1
            ;;
    esac
fi

exit 0


