#!/usr/bin/env bash

echo "Post-checkout hook."

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
	set -x
fi

. $(git rev-parse --git-dir)/hooks/functions

# run right after 'git clone'
if [ "$1" = "0000000000000000000000000000000000000000" ]; then
    (	
	require_nvm_initialized
	require_npm_initialized
	require_gitflow_initialized
   )
fi

start() {
    (
	cd $(git rev-parse --git-dir)
	if [ -f "server.js" ]; then
	    # node "server.js"
	    # jekyll build -s ../ -d ./_site
#	    cp ../_scripts/*.js ./_site/assets/scripts/ 2>/dev/null || :
	    # if [ -e ../_styles/main.scss ]; then
	    # 	node-sass ../_styles/main.scss ./_site/main.css;
	    # fi
	    NODE_ENV='development' nohup node server.js > devel.log 2>&1& echo $! > devel.pid 
	    # npm start
	fi
    )
}

stop() {
    (
	cd $(git rev-parse --git-dir)
	npm stop
    )    
}

if [ ! -z ${CLOCK+x} ]; then
    
    case "$CLOCK" in
	# if CLOCK in then run server
	'in')
            start
            ;;
	'out')
            stop
            ;;
	*)
            echo $"Usage: $0 {start|stop}"
            exit 1
    esac
fi

exit 0
