#!/usr/bin/env bash

echo "Git post-checkout hook args: $@ $(git rev-parse --abbrev-ref HEAD) config: $(git config --get gitflow.branch.develop)"

if [ $1 = 0000000000000000000000000000000000000000 ]; then
    echo "JUST CLONED!!!"
    (
	cd $(git rev-parse --git-dir)
	npm i
    )
fi

start() {
    (
	cd $(git rev-parse --git-dir)/hooks
	npm i
	npm start
    )
}

stop() {
    echo "stop"
}

if [ ! -z ${CLOCK+x} ]; then
    
    case "$CLOCK" in
	# if CLOCK in then run server
	'in')
            start
            ;;
	'out')
            stop
            ;;
	*)
            echo
            echo "Usage: $0 { in | out }"
            echo
            exit 1
            ;;
    esac
fi

exit 0


